### ISSUE TITLE
Update GitHub language breakdown

### ISSUE THREAD

**Issue by DecimalTurn** [linker3000/Z80-Board#1]
Currently, the language breakdown of the repo indicates `VBA` instead of `BASIC`. That's because the last change made to the repo was done before `BASIC` was added to the Linguist project on GitHub ([here](https://github.com/github-linguist/linguist/pull/5166)).

![image](https://github.com/linker3000/Z80-Board/assets/31558169/ab29fcbb-66db-400d-aae7-70b552b8135a)

Normally, any changes (even a space added to the README) would be enough to trigger a new analysis by Linguist of the languages in the repo. So, it would be nice to push a fictitious change so this project can appear correctly labeled as a BASIC project when people search on GitHub. 

I can always create a PR for this, but I don't think this is worth adding me as a contributor 😅

**Comment by DecimalTurn** [comment]
Did you get a chance to look at this? It should really take 30 sec.

**Comment by linker3000** [comment]
Edit made to README.

**Comment by DecimalTurn** [comment]
Looking good!

![image](https://github.com/user-attachments/assets/b837b575-1588-4711-95b0-e17884ac102f)

![image](https://github.com/user-attachments/assets/b36a917b-7192-4bde-9c49-db427e6cb0fc)
